version: "3.5"

services:
  aiassist-server-service:
    container_name: aiassist-server-service-container
    build:
      context: ./
      dockerfile: ./aiassist-server/Dockerfile
    ports:
      - 3100:3100
    volumes:
      - ./aiassist-server:/app
    restart: always

  aiassist-client-service:
    container_name: aiassist-client-service-container
    build: 
      context: ./
      dockerfile: ./aiassist-client/Dockerfile
    ports:
      - 5174:5174
    volumes:
      - ./aiassist-client:/app
    
  mongo:
    ports:
      - '27017:27017'
    container_name: dkrcomp-mongo
    restart: always
    logging:
      options:
        max-size: 100m
    env_file:
      - ./aiassist-server/.env
    image: mongo
