version: "3.5"

services:
  aiassist-server-service:
    container_name: aiassist-server-service-container
    build: ./aiassist-server
    ports:
      - 3100:3100
    volumes:
      - ./aiassist-server:/app
      - /app/node_modules
    restart: always

  aiassist-client-service:
    container_name: aiassist-client-service-container
    build: ./aiassist-client
    ports:
      - 5174:5174
    volumes:
      - ./aiassist-client:/app
      - /app/node_modules
    
  mongo:
    ports:
      - '27017:27017'
    container_name: dkrcomp-mongo
    restart: always
    logging:
      options:
        max-size: 100m
    env_file:
      - ./aiassist-server/.env
    image: mongo
