version: "3.5"

services:
  aiassist-server-service:
    container_name: aiassist-server-container
    build:
      context: ../
      dockerfile: ./docker/server/Dockerfile
    ports:
      - 3100:3100
    environment:
      - OPENAI_API_KEY=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
    volumes:
      - ../aiassist-server:/usr/src/app
    restart: always

  aiassist-client-service:
    container_name: aiassist-client-service-container
    build: 
      context: ../
      dockerfile: ./docker/client/Dockerfile
    ports:
      - 5174:5174
    volumes:
      - ../aiassist-client:/usr/src/app
      - /usr/src/app/node_modules
    
  mongo:
    ports:
      - '27017:27017'
    container_name: dkrcomp-mongo
    restart: always
    logging:
      options:
        max-size: 100m
    env_file:
      - ../aiassist-server/.env
    image: mongo
